[package]
name = "rustycasc"
version = "0.2.1"
edition = "2018"
authors = ["ferronn@ferronn.dev"]
description = "Parses CASC and generates FrameXML extracts"
repository = "https://github.com/ferronn-dev/rustycasc"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.104"
async-trait = "0.1.91"
bytes = "1.12.1"
clap = { version = "4.6.4", features = ["derive"] }
derive_more = { version = "2.1.1", features = ["display"] }
futures = "0.3.33"
hashers = "1.0.1"
hex = "0.4.3"
indicatif = "0.18.6"
itertools = "0.15.0"
log = "0.4.33"
mail-parser = "0.11.5"
md5 = "0.8.1"
miniz_oxide = "0.9.1"
nom = "8.0.0"
nom-derive = "0.10.1"
regex = "1.13.1"
reqwest = "0.13.4"
sha2 = "0.11.0"
stderrlog = "0.6.0"
tokio = { version = "1.53.1", features = ["fs", "macros", "rt-multi-thread", "time"] }
velcro = "0.5.4"
xml-rs = "1.0.0"
zip = "8.6.0"
